### ISSUE TITLE
Not working on iOS 13

### ISSUE THREAD

**Issue by francisco-alvarado-espol** [hansemannn/titanium-ios-document-picker#7]
I already make the snippet to show the Files app popover, but at the momento to select any pdf, the success callback doesn't work. I've tried with other delegate methods, but what I've discover is that in the success callback, the urls parameter returns an empty NSArray.

**Comment by sanmanborate** [comment]
@falvarado-espol Can you help me with how to import this module in titanium. I am unable to import it into my code. Also the line 'export default class TiDocumentPicker' shows error as 'syntax error unexpected token export'.  Attaching error message & widgets folder screenshot.
<img width="314" alt="Screenshot 2020-04-04 at 11 11 57 AM" src="https://user-images.githubusercontent.com/24290846/78419635-446d2700-7665-11ea-8a7c-c03ab2f254cc.png">
<img width="264" alt="Screenshot 2020-04-04 at 11 12 16 AM" src="https://user-images.githubusercontent.com/24290846/78419637-4636ea80-7665-11ea-8f83-4ff81ee60cdd.png">

**Comment by ebruchanow** [comment]
Hello, i have the same Problem. Working on iOS 14 and Titanium SDK 9.2.1. When i try to import the module, it says the module is not supported by the SDK. Any Chance the module will be updated or is there any other fix for this? Thanks in Advance

**Comment by hansemannn** [comment]
I just updated the module
