### ISSUE TITLE
Getting error with Ti.SDK 10.0.0

### ISSUE THREAD

**Issue by reactnative103** [hansemannn/titanium-ios-document-picker#8]
Hi Hans,

I am getting below error while trying to run the application.

**Error:** 
unknown encoding [UIDocumentMenuViewController][UIDocumentPickerViewController] start at index 0
Process exited with 1
The terminal process terminated with exit code: 1.

Also I have updated the latest code in both the file (index.js & document-picker-delegate.js).

Can you please help?

**Note:** Working fine with the 9.3.2 SDK. 
I have also tried to require 2.0.0 module but it's now working. Could you please share the example like how to use it?

Thanks,

**Comment by hansemannn** [comment]
I just open sourced the newer version of this module: https://github.com/hansemannn/titanium-document-picker

This one will be archived
